name: zeuscajurao
description: A personal website that contains info about my journey as a software developer.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.4
  url_launcher: ^6.1.4
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/mockups/
    - assets/images/mockups/car/
    - assets/images/mockups/shapeyou/
    - assets/images/mockups/khephren/
  fonts:
    - family: M
      fonts:
        - asset: assets/font/t.ttf
          weight: 100
        - asset: assets/font/ti.ttf
          style: italic
          weight: 100
        - asset: assets/font/el.ttf
          weight: 200
        - asset: assets/font/eli.ttf
          style: italic
          weight: 200
        - asset: assets/font/l.ttf
          weight: 300
        - asset: assets/font/li.ttf
          style: italic
          weight: 300
        - asset: assets/font/r.ttf
          weight: 400
        - asset: assets/font/ri.ttf
          style: italic
          weight: 400
        - asset: assets/font/m.ttf
          weight: 500
        - asset: assets/font/mi.ttf
          style: italic
          weight: 500
        - asset: assets/font/sb.ttf
          weight: 600
        - asset: assets/font/sbi.ttf
          style: italic
          weight: 600
        - asset: assets/font/bo.ttf
          weight: 700
        - asset: assets/font/boi.ttf
          style: italic
          weight: 700
        - asset: assets/font/ebo.ttf
          weight: 800
        - asset: assets/font/eboi.ttf
          style: italic
          weight: 800
        - asset: assets/font/bl.ttf
          weight: 900
        - asset: assets/font/bli.ttf
          style: italic
          weight: 900
