name: zeuscajurao
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.4
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # - family: QuickSand
    #   fonts:
    #     - asset: assets/fonts/Quicksand-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Quicksand-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Quicksand-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Quicksand-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Quicksand-Bold.ttf
    #       weight: 700
    - family: Alumni
      fonts:
        - asset: assets/fonts/AlumniSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/AlumniSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/AlumniSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AlumniSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/AlumniSans-Light.ttf
          weight: 300
        - asset: assets/fonts/AlumniSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/AlumniSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlumniSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/AlumniSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlumniSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/AlumniSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlumniSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/AlumniSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlumniSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlumniSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlumniSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/AlumniSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlumniSans-BlackItalic.ttf
          style: italic
          weight: 900
